services:
  db:
    image: "postgres:16.0"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGUSER
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
  api:
    build: backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL
    depends_on:
      db:
        condition: service_healthy
