"""add project column to in-item

Revision ID: b84e41b8243c
Revises: 2ab6fd5825fd
Create Date: 2023-11-17 21:55:06.209960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84e41b8243c'
down_revision = '2ab6fd5825fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_item', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'in_item', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'in_item', type_='foreignkey')
    op.drop_column('in_item', 'project_id')
    # ### end Alembic commands ###
